# Generated by Django 6.0.7 on 2026-07-16 09:41

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="hospitalappuser",
            managers=[
                ("objects", api.models.HospitalAppUserManager()),
            ],
        ),
    ]
